# typed: false
# frozen_string_literal: true

# Rendered by .github/workflows/release.yml on each v* tag.
# Tokens substituted: 1.0.0, 1c0bba43aedb1cccba2aca624ac069454bb13f472f20cc191bea64aed282014b.
class BigCodeAnalysis < Formula
  desc "Compute maintainability metrics for source code in many languages"
  homepage "https://github.com/dekobon/big-code-analysis"
  version "1.0.0"
  license "MPL-2.0"

  # Apple-silicon-only. Intel Macs install via `cargo install
  # big-code-analysis-cli` / `cargo install big-code-analysis-web`
  # or run the aarch64 build under Rosetta 2. GitHub's macos-13
  # runner pool was too oversubscribed to justify keeping Intel in
  # the release matrix.
  on_macos do
    on_arm do
      url "https://github.com/dekobon/big-code-analysis/releases/download/v#{version}/big-code-analysis-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "1c0bba43aedb1cccba2aca624ac069454bb13f472f20cc191bea64aed282014b"
    end
  end

  def install
    bin.install "bca"
    bin.install "bca-web"
    # Per-binary TPL — bca and bca-web have non-overlapping direct
    # deps (clap/ignore vs actix-web/tokio/futures), so we ship two
    # notices files rather than a merged one that would
    # under-attribute one side.
    doc.install "README.md", "LICENSE", "CHANGELOG.md",
                "THIRD-PARTY-LICENSES-bca.md",
                "THIRD-PARTY-LICENSES-bca-web.md"
    # Man pages — `bca.1`, `bca-web.1`, plus one `bca-<sub>.1` per
    # subcommand. Generated by the workspace `xtask` and staged under
    # the tarball's `man/` directory by the release workflow.
    man1.install Dir["man/*.1"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bca --version")
    assert_match version.to_s, shell_output("#{bin}/bca-web --version")
  end
end
